const food = [
    "Sushi",
    "Marisco",
    "Vinho Tinto",
    "Grão de bico",
    "Pizza",
    "Lasanha",
    "Peixei frito",
    "Peixe assado",
    "Pudim",
    "Chocolate",
    "Mostarda",
    "Bolo de aniversário",
    "Ovo",
    "Ovo de Codorna",
    "Hot Dog",
    "Cereja",
    "Moranga",
    "Morango",
    "Cenoura",
    "Bolo de cenoura",
    "Bolo de chocolate",
    "Brócolis",
    "Cereja",
    "Framboesa",
    "Repolho",
    "Carne de cordeiro",
    "Damasco",
    "Coco",
    "Carne de porco",
    "Cereais",
];

module.exports = { food };
