const places = [
    "Hospital",
    "Praia",
    "Cidade",
    "Fazenda",
    "Riacho",
    "Lagoa",
    "Aeroporto",
    "Escola",
    "Banco",
    "Mercado",
    "Feira",
    "Deserto",
    "Cascata",
    "Cachoeira",
    "Balada",
    "Cassino",
    "Motel",
    "Hotel",
    "Estação de Trem",
    "Parque",
    "Agência dos correios",
    "Biblioteca",
    "Restaurante",
    "Cinema",
    "Zoológico",
    "Igreja",
    "Padaria",
    "Livraria",
    "Farmácia",
    "Casa",
    "Apartamento",
    "Cafeteria",
    "Barbeiro",
    "Banheiro Químico",
    "Garagem",
    "Museu",
    "Posto de bombeiros",
    "Delegacia de polícia",
    "Estádio de futebol",
    "Campo de golf",
    "Quadra de basquete",
    "Presídio",
    "Posto de pedágio",
    "Açougue",
    "Alfaiataria",
    "Petshop",
    "Leroy Merlin",
    "Havan Rio Grande",
    "Universidade Federal do Rio Grande",
    "Centro de Ciências Computacionais",
];

module.exports = { places };
