const professions = [
    "Professor",
    "Ator",
    "Bombeiro",
    "Açougueiro",
    "Cabeleireiro",
    "Enfermeira",
    "Agricultor",
    "Taxista",
    "Técnico elétrico",
    "Arquiteto",
    "Farmacêutico",
    "Carteiro",
    "Padeiro",
    "Vendedora",
    "Dona de casa",
    "Sapateiro",
    "Astronauta",
    "Carteiro",
    "Dependente",
    "Youtuber",
    "Bombeiro",
    "Cantor",
    "Engenheiro",
    "Enfermeira",
    "Arqueólogo",
    "Taxista",
    "Jornalista",
    "Caixa",
    "Carpinteiro",
    "Motorista",
    "Dentista",
    "Advogada",
    "Faxineira",
    "Programador",
    "Empresário",
];

module.exports = { professions };
